apiVersion: weblogic.oracle/v9
kind: Domain
metadata:
  name: sample-domain
  namespace: weblogic-sample
spec:
  domainHome: /u01/domains/sample-domain
  domainHomeSourceType: FromModel
  image: ${IMAGE}
  imagePullSecrets:
    - name: ${IMAGE_PULL_SECRET_NAME}
  webLogicCredentialsSecret:
    name: weblogic-credentials
  includeServerOutInPodLog: true
  serverStartPolicy: IF_NEEDED
  serverPod:
    env:
      - name: JAVA_OPTIONS
        value: -Dweblogic.StdoutDebugEnabled=false
  adminServer:
    adminService:
      channels:
        - channelName: default
          nodePort: 32001
  clusters:
    - clusterName: cluster-1
      replicas: 1
  configuration:
    model:
      domainType: WLS
      runtimeEncryptionSecret: runtime-encryption-secret
    secrets:
      - weblogic-credentials
      - runtime-encryption-secret
